spring.datasource.url=${DB_URL:jdbc:mysql://localhost/forum_hub}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.application.name=forum.hub

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET}

api.security.token.expiration=2

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true